NGUK-520_optional_filter_fields
piklema/mqtt-kafka-connector pull request #22
Opened 2023-12-08 12:04 UTC by riros

Опциональные фильтрации:
*  NaN, INF - выключена по умолчанию
* none - включена по умолчанию
Добавил pre-commit

Пересоздал PR, Извините.

2023-12-08 12:19 UTC, SergeyDubovitsky commented on .pre-commit-config.yaml
> +#            -   id: lint/isort
комментарии

2023-12-08 12:32 UTC, riros commented on .pre-commit-config.yaml
> +#            -   id: lint/isort
Удалил

2023-12-11 08:54 UTC, deliseev commented on src/mqtt_kafka_connector/connector/main.py
> +            f'Message received from {mqtt_topic.value=} ' f'{message.payload=} {message.qos=}',
Не использовать f-строки в логгерах

2023-12-11 08:54 UTC, deliseev commented on src/mqtt_kafka_connector/connector/main.py
> +            logger.warning(f'Error prepare kafka topic from {mqtt_topic.value=}')
Тут тоже

2023-12-11 08:54 UTC, deliseev commented on src/mqtt_kafka_connector/utils.py
> +    return ''.join(f'{c:0>8b}' for c in struct.pack('d', num))
Для чего это?

2023-12-11 08:54 UTC, deliseev commented on src/mqtt_kafka_connector/utils.py
> +    if isinstance(input_dict, dict):
Если мы убрали совместимость со старыми версиями питона, то здесь можно задействовать case..match

2023-12-11 08:54 UTC, deliseev commented on src/mqtt_kafka_connector/utils.py
> +    if isinstance(input_dict, dict):
И тут

2023-12-11 08:54 UTC, deliseev commented on src/mqtt_kafka_connector/utils.py
> +        return {k: v for k, v in ((k, clean_empty_fields(v)) for k, v in input_dict.items()) if v}
Тут если v=False - то отфильтруется, такое поведение нужно?

2023-12-11 08:54 UTC, deliseev commented on tests/riros.py
> +import dataclasses
Файл с тестами должен начинаться с `test_что-то там`

2023-12-11 08:54 UTC, deliseev commented on tests/test_utils.py
> +        "e": None,
Попробуй добавить `"f": False` - оно отфильтруется

2023-12-11 08:54 UTC, deliseev commented on pyproject.toml
> +    "ignore::django.conf.RemovedInDjango50Warning",
Django тут нет

2023-12-11 08:54 UTC, deliseev commented on src/mqtt_kafka_connector/__init__.py
> +if "src" not in sys.path:
Такая проверке не корректна

2023-12-11 08:54 UTC, deliseev commented on src/mqtt_kafka_connector/__init__.py
> +    sys.path.append(str(os.path.join(BASE_DIR, "src")))
```suggestion
    sys.path.append(str(BASE_DIR / 'src'))
```

2023-12-11 09:09 UTC, riros commented on src/mqtt_kafka_connector/connector/main.py
> +            f'Message received from {mqtt_topic.value=} ' f'{message.payload=} {message.qos=}',
Почему ?

2023-12-11 09:26 UTC, RuslanDa commented on src/mqtt_kafka_connector/connector/main.py
> +            f'Message received from {mqtt_topic.value=} ' f'{message.payload=} {message.qos=}',
https://docs.python.org/3/howto/logging.html#optimization

2023-12-11 09:42 UTC, riros commented on src/mqtt_kafka_connector/connector/main.py
> +            f'Message received from {mqtt_topic.value=} ' f'{message.payload=} {message.qos=}',
почитал. Исправлю.

2023-12-11 09:55 UTC, riros commented on src/mqtt_kafka_connector/utils.py
> +    return ''.join(f'{c:0>8b}' for c in struct.pack('d', num))
Убрал в блокнот. riros.py

2023-12-11 09:55 UTC, riros commented on src/mqtt_kafka_connector/utils.py
> +    if isinstance(input_dict, dict):
Выглядит хуже. Кода больше.

2023-12-11 10:17 UTC, riros commented on tests/riros.py
> +import dataclasses
Да, но если надо, чтобы он не запускался вместе с другими, а запускался только вручную. То можно так назвать. 
Идея была - не запускаться его через pytest команду.

2023-12-11 10:20 UTC, riros commented on tests/test_utils.py
> +        "e": None,
Убрал функцию

2023-12-11 10:24 UTC, riros commented on src/mqtt_kafka_connector/__init__.py
> +if "src" not in sys.path:
Исправил.

2023-12-11 10:26 UTC, riros commented on src/mqtt_kafka_connector/utils.py
> +    if isinstance(input_dict, dict):
Некрасиво будет.

2023-12-11 11:16 UTC, riros commented on pyproject.toml
> +    "ignore::django.conf.RemovedInDjango50Warning",
Исправил

2023-12-11 11:16 UTC, riros commented on src/mqtt_kafka_connector/__init__.py
> +    sys.path.append(str(os.path.join(BASE_DIR, "src")))
Сделал

2023-12-11 12:00 UTC, riros commented on tests/riros.py
> +import dataclasses
удалил файл

2023-12-11 12:01 UTC, riros commented on src/mqtt_kafka_connector/utils.py
> +        return {k: v for k, v in ((k, clean_empty_fields(v)) for k, v in input_dict.items()) if v}
удалил функцию.

2023-12-11 13:17 UTC, deliseev requested changes

2023-12-11 13:17 UTC, deliseev commented on tests/conftest.py
> +@pytest.fixture()
```suggestion
@pytest.fixture
```

2023-12-11 13:17 UTC, deliseev commented on tests/riros.py
> +    code = model_generator.render(schema=TestModel.generate_schema())
Зачем? Во-первых это у нас не используется, а во-вторых зачем нам тестировать функциональность внешней библиотеки (dataclasses_avroschema) ?

2023-12-11 13:17 UTC, deliseev commented on tests/riros.py
> +    assert a_orjson_dump != a_json_dump  # NaN -> none
Тут по сути тестирование внешних библиотек (json, orjson) никакого своего кода ты здесь не тестируешь

2023-12-11 13:22 UTC, riros commented on tests/conftest.py
> +@pytest.fixture()
./tests/conftest.py:8:2: PT001 use @pytest.fixture() over @pytest.fixture
flake8 ругается.  Может это правильно ?

2023-12-11 13:24 UTC, riros commented on tests/riros.py
> +    code = model_generator.render(schema=TestModel.generate_schema())
Этот файл был для меня.

2023-12-11 13:26 UTC, deliseev commented on tests/conftest.py
> +@pytest.fixture()
https://docs.pytest.org/en/6.2.x/reference.html#fixtures

2023-12-11 13:26 UTC, riros commented on tests/riros.py
> +    assert a_orjson_dump != a_json_dump  # NaN -> none
Я не доверяю идеальности мира. Иногда перепроверяю. 
Этим я просто хотел показать, что было сделано. и оставить для себя памятку. Файл давно уже удален.

2023-12-11 13:26 UTC, deliseev commented on tests/conftest.py
> +@pytest.fixture()
Возможно можно и со (), но в официально документации показано без них

2023-12-11 13:27 UTC, riros commented on tests/riros.py
> +    code = model_generator.render(schema=TestModel.generate_schema())
Я это тестировал, чтобы понять, как это можно использовать. Если не используется у вас то все, мне не использовать?

2023-12-11 14:56 UTC, riros commented on tests/conftest.py
> +@pytest.fixture()
убрал

2023-12-12 07:46 UTC, deliseev approved these changes

2023-12-12 07:47 UTC, SergeyDubovitsky approved these changes

2023-12-12 08:00 UTC, merged