DA-978: Эмулятор данных телеметрии
piklema/mqtt-kafka-connector pull request #4
Opened 2023-04-03 16:28 UTC by sd1piklema

Команда в mqtt-kafka-connector читающая данные телеметрии из csv файла с перекладыванием json в кафку.

2023-04-04 08:31 UTC, SergeyDubovitsky requested changes

2023-04-04 08:31 UTC, SergeyDubovitsky commented on connector/test.cfg
> +# id из файла, id для отправки
блин не очень выглядит такое конфигурирование

2023-04-04 10:01 UTC, RuslanDa requested changes

2023-04-04 10:01 UTC, RuslanDa commented on connector/send.py
> +                logger.debug('Publishing to %s', topic)
f-string

2023-04-04 10:06 UTC, deliseev commented on connector/send.py
> +                logger.debug('Publishing to %s', topic)
https://docs.python.org/3/howto/logging.html#optimization

2023-04-04 10:13 UTC, SergeyDubovitsky commented on connector/send.py
> +                logger.debug('Publishing to %s', topic)
вообще через   %  правильнее)) лоигование оптимизировано под это

2023-04-04 10:13 UTC, SergeyDubovitsky commented on connector/send.py
> +                logger.debug('Publishing to %s', topic)
но все закрывают глаза и делают f стринги тк удобнее

2023-04-04 14:03 UTC, RuslanDa commented on connector/send.py
> +                logger.debug('Publishing to %s', topic)
Понял, не знал

2023-04-04 14:03 UTC, RuslanDa approved these changes

2023-04-06 06:23 UTC, SergeyDubovitsky requested changes

2023-04-06 06:23 UTC, SergeyDubovitsky commented on connector/send.py
> +    parser.add_argument(
лишнее

2023-04-06 06:23 UTC, SergeyDubovitsky commented on src/mqtt_kafka_connector/clients/mqtt.py
> +class MQTTClient:
они нигде не используется же

2023-04-06 15:32 UTC, deliseev commented on src/mqtt_kafka_connector/clients/mqtt.py
> +class MQTTClient:
✅

2023-04-06 15:32 UTC, deliseev commented on connector/send.py
> +    parser.add_argument(
✅

2023-04-06 15:33 UTC, deliseev commented on connector/test.cfg
> +# id из файла, id для отправки
🤷🏻

2023-04-06 17:24 UTC, merged