PK-369
piklema/mqtt-kafka-connector pull request #6
Opened 2023-05-03 13:35 UTC by deliseev

2023-05-03 13:43 UTC, SergeyDubovitsky requested changes

2023-05-03 13:43 UTC, SergeyDubovitsky commented on src/mqtt_kafka_connector/connector/main.py
> +            assert type(data) == bytes
вот такое же нельзя)

2023-05-03 13:43 UTC, SergeyDubovitsky commented on src/mqtt_kafka_connector/connector/main.py
> +                messages = json.loads(data.decode())['messages']
чот упростить никак? в 117 encode тут decode в 136 снова encode

2023-05-03 13:43 UTC, SergeyDubovitsky commented on src/mqtt_kafka_connector/emu/main.py
> +            d = asdict(tt)
непонятно что такое tt ?

2023-05-03 13:43 UTC, deliseev commented on src/mqtt_kafka_connector/connector/main.py
> +            assert type(data) == bytes
почему?

2023-05-05 08:09 UTC, SergeyDubovitsky approved these changes

2023-05-11 08:30 UTC, merged